name: Publish package Avro Tool to Github Packages

on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
      - name: Deploy
        run: mvn -B -Pgithub --settings ./settings.xml deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
          MAVEN_GITHUB_USERNAME: ${{ secrets.MAVEN_GITHUB_USERNAME }}
          MAVEN_GITHUB_PASSWORD: ${{ secrets.MAVEN_GITHUB_PASSWORD }}